name: Django-app workflow

on: [push]

jobs:
  tests:
    name: Testing with flake8 and django
    runs-on: ubuntu-latest

    steps:
      - name: check GitHub branches
        uses: actions/checkout@v2

      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: update pip, install flake8 and dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r api_yamdb/requirements.txt
      - name: Run flake8 and pytest
        run: |
          python -m flake8 
          # pytest

  build_and_push_to_docker_hub:
    name: Pushing Docker image to Docker Hub
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: api_yamdb/
          file: api_yamdb/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api_yamdb:latest
